In [1]:
from lib import *

In [2]:
hidden_layer1 = HiddenLayer(name="test0",input_shape=3, output_shape=2, weights=None, activation_function="sigmoid")
hidden_layer2 = HiddenLayer(name="test1",input_shape=2, output_shape=1, weights=None, activation_function="relu")
output_layer = OutputLayer(name="test1",input_shape=2, output_shape=1, weights=None, activation_function="linear")

In [3]:
the_model = Model("model_test",ANN(3,1))
the_model.summary()

Summary for Model: model_test


In [4]:
the_model.add(hidden_layer1)
the_model.add(hidden_layer2)
the_model.add(output_layer)
the_model.summary()

Summary for Model: model_test
Layer: test0 - hidden
Layer: test1 - hidden
Layer: test1 - output


In [5]:
#perform testing of output layer
#initialize weight for single perceptron
import numpy as np
w = np.array([
        [0.1, 0.2, 0.3],
        [0.4, -0.5, 0.6],
        [0.7, 0.8, -0.9]
      ])

print(w)

[[ 0.1  0.2  0.3]
 [ 0.4 -0.5  0.6]
 [ 0.7  0.8 -0.9]]


In [6]:
#example input:
input_array = np.array([[-1.0, 0.5]])
# append the first column of 1s
print(input_array)

[[-1.   0.5]]


In [7]:
dummy_output_layer = OutputLayer(name="test1",input_shape=2, output_shape=3, weights=w, activation_function="relu")

In [8]:
print(dummy_output_layer.forward_propagation(input_array))

[[0.05 1.1  0.  ]]
