In [1]:
from lib import *

In [2]:
the_model = Model("model_test",ANN(3,1))
the_model.summary()

Summary for Model: model_test


In [3]:
#perform testing of output layer
#initialize weight for single perceptron
import numpy as np
w0 = np.array([
        [0.1, 0.2, 0.3],
        [0.4, -0.5, 0.6],
        [0.7, 0.8, -0.9]
      ])

w1 = np.array([[-1.0,0.5],
                [1.0,0.5],
                [1.0,0.5], 
                [1.0,0.5]])


In [4]:
#example input:
input_array = np.array([[-1.0, 0.5]])
# append the first column of 1s
print(input_array)

[[-1.   0.5]]


In [5]:
dummy_hidden_layer = HiddenLayer(name="hidden1",input_shape=2, output_shape=3, weights=w0, activation_function="relu")
dummy_output_layer = OutputLayer(name="output1",input_shape=3, output_shape=2, weights=w1, activation_function="softmax")

In [6]:
model = Model("model_test",ANN(2,2))

In [7]:
model.add(dummy_hidden_layer)
model.add(dummy_output_layer)

In [8]:
model.summary()

Summary for Model: model_test
Layer: hidden1 | Type: hidden | Output shape: 3
Weights:
 [[ 0.1  0.2  0.3]
 [ 0.4 -0.5  0.6]
 [ 0.7  0.8 -0.9]]
_____________________________________
Layer: output1 | Type: output | Output shape: 2
Weights:
 [[-1.   0.5]
 [ 1.   0.5]
 [ 1.   0.5]
 [ 1.   0.5]]


In [9]:
model.predict(input_array)

array([[0.28394021, 0.71605979]])