In [1]:
from lib import *

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
data = PreProcessing()

In [4]:
parser = BackPropParser("../test_case/B/linear_small_lr.json")

In [5]:
the_model = parser.build_model()

In [6]:
the_model.summary()

Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: linear
Weights:
 [[ 0.1  0.3  0.2]
 [ 0.4  0.2 -0.7]
 [ 0.1 -0.8  0.5]]


In [7]:
the_model.fit(parser.input, parser.target, parser.max_iteration, parser.learning_rate, parser.batch_size, error_threshold=parser.error_threshold)

Epoch 1 completed
Loss: 0.665


In [8]:
the_model.summary()

Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: linear
Weights:
 [[ 0.1012  0.3006  0.1991]
 [ 0.4024  0.201  -0.7019]
 [ 0.1018 -0.799   0.4987]]


In [9]:
processor = PreProcessing()
processor.readCSV("../test_case/testcase_dataset/iris.csv")

In [10]:
df = processor.data_frame

In [11]:
#change the species to one hot encoding, example: [0,0,1] 
Y = pd.get_dummies(df['Species'])
#change from boolean to int
Y = Y.astype(np.float64)

X = df.drop(columns=['Id','Species'])

#preprocess Y 


In [19]:
X_train, X_valid, y_train, y_valid = train_test_split(X, Y, test_size=0.2, random_state=42)

In [20]:
# to numpy array
X_train = X_train.to_numpy()
X_valid = X_valid.to_numpy()
y_train = y_train.to_numpy()
y_valid = y_valid.to_numpy()

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)

In [33]:
#predict
the_model = Model("Iris", ANN(len(X_train[0]), len(y_train[0]), 0.1, 100))

In [34]:
the_model.add(HiddenLayer("Hidden_1",len(X_train[0]), 5, np.ones((len(X_train[0])+1, 5)), "relu"))
the_model.add(HiddenLayer("Hidden_2",5, 3, np.ones((6, 3)), "relu"))
the_model.add(OutputLayer("Output",3, 3, np.ones((4, 3)), "softmax", None))

In [37]:
the_model.fit(X_train, y_train, 1000, 0.1, 10, error_threshold=0.01, X_valid=X_valid, Y_valid=y_valid)

Epoch 1 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 2 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 3 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 4 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 5 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 6 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 7 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 8 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 9 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 10 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 11 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 12 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 13 completed
Loss: 1.1324481712329912
Accuracy: 36.666666666666664%
Epoch 14 completed
Loss: 1.1324481712329912
Acc