In [1]:
from lib import *

In [2]:
the_model = Model("model_test",ANN(3,1))
the_model.summary()

Summary for Model: model_test


In [3]:
#perform testing of output layer
#initialize weight for single perceptron
import numpy as np
w0 = np.array([
        [0.1, 0.2, 0.3],
        [0.4, -0.5, 0.6],
        [0.7, 0.8, -0.9]
      ])

w1 = np.array([[-1.0,0.5],
                [1.0,0.5],
                [1.0,0.5], 
                [1.0,0.5]])


In [4]:
#example input:
input_array = np.array([[-1.0, 0.5]])
# append the first column of 1s
print(input_array)

[[-1.   0.5]]


In [5]:
# dummy_hidden_layer = HiddenLayer(name="hidden1",input_shape=2, output_shape=3, weights=w0, activation_function="relu")
# dummy_output_layer = OutputLayer(name="output1",input_shape=3, output_shape=2, weights=w1, activation_function="softmax")

In [6]:
parser = Parser("../test_case/relu.json")

<class 'int'>
[-1.   0.5]


In [7]:
model = Model("model_test",ANN(parser.getInputSize(),parser.getOutputSize()))

In [8]:
parser.addAllLayers(model)

In [9]:
# model.add(dummy_hidden_layer)
# model.add(dummy_output_layer)

In [10]:
model.summary()

Summary for Model: model_test
Layer: hidden1 | Type: hidden | Output shape: 3
Weights:
 [[ 0.1  0.2  0.3]
 [ 0.4 -0.5  0.6]
 [ 0.7  0.8 -0.9]]
_____________________________________


In [11]:
model.save("oke.pkl")

Summary for Model: model_test
Layer: hidden1 | Type: hidden | Output shape: 3
Weights:
 [[ 0.1  0.2  0.3]
 [ 0.4 -0.5  0.6]
 [ 0.7  0.8 -0.9]]
_____________________________________


In [12]:
model.predict(input_array)

array([[0.05, 1.1 , 0.  ]])

In [13]:
#perform another test
model = Model("model_softmax",ANN(8,3))

In [14]:
input_array_2 = np.array([[-1.0, 1.0, 2.8, 1.8, -0.45, 0.24, 0.15, 0.2]])

In [15]:
w3 = np.array([
        [0.1, 0.9, -0.1],
        [-0.2, 0.8, 0.2],
        [0.3, -0.7, 0.3],
        [0.4, 0.6, -0.4],
        [0.5, 0.5, 0.5],
        [-0.6, 0.4, 0.6],
        [-0.7, -0.3, 0.7],
        [0.8, 0.2, -0.8],
        [0.9, -0.1, 0.0]
      ])

In [16]:
dummy_softmax_layer = OutputLayer(name="softmax",input_shape=8, output_shape=3, weights=w3, activation_function="softmax")

In [17]:
model.add(dummy_softmax_layer)
model.summary()

Summary for Model: model_softmax
Layer: softmax | Type: output | Output shape: 3
Weights:
 [[ 0.1  0.9 -0.1]
 [-0.2  0.8  0.2]
 [ 0.3 -0.7  0.3]
 [ 0.4  0.6 -0.4]
 [ 0.5  0.5  0.5]
 [-0.6  0.4  0.6]
 [-0.7 -0.3  0.7]
 [ 0.8  0.2 -0.8]
 [ 0.9 -0.1  0. ]]


In [18]:
model.predict(input_array_2)

array([[0.76439061, 0.21168068, 0.02392871]])

yah sesuai sama tc asisten, so far