In [1]:
from lib import *

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
def fit(the_model, parser):
    the_model.fit(parser.input, parser.target, parser.max_iteration, parser.learning_rate, parser.batch_size, error_threshold=parser.error_threshold)

## TestCase for linear_small_lr

In [4]:
parser = BackPropParser("../test_case/B/linear_small_lr.json")
the_model = parser.build_model()
the_model.summary()




Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: linear
Weights:
 [[ 0.1  0.3  0.2]
 [ 0.4  0.2 -0.7]
 [ 0.1 -0.8  0.5]]


In [5]:
fit(the_model, parser)

Start Training for MLP
Epoch 1 completed
Loss: 0.665
Training Accuracy: 100.0%


In [6]:
the_model.summary()

Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: linear
Weights:
 [[ 0.1012  0.3006  0.1991]
 [ 0.4024  0.201  -0.7019]
 [ 0.1018 -0.799   0.4987]]


## TestCase for linear_two_iteration

In [7]:
parser = BackPropParser("../test_case/B/linear_two_iteration.json")
the_model = parser.build_model()
the_model.summary()




Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: linear
Weights:
 [[ 0.1  0.3  0.2]
 [ 0.4  0.2 -0.7]
 [ 0.1 -0.8  0.5]]


In [8]:
fit(the_model, parser)

Start Training for MLP
Epoch 1 completed
Loss: 0.665
Training Accuracy: 100.0%
Epoch 2 completed
Loss: 0.1818499999999999
Training Accuracy: 100.0%


In [9]:
the_model.summary()

Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: linear
Weights:
 [[ 0.166  0.338  0.153]
 [ 0.502  0.226 -0.789]
 [ 0.214 -0.718  0.427]]


## TestCase for linear

In [10]:
parser = BackPropParser("../test_case/B/linear.json")
the_model = parser.build_model()
the_model.summary()




Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: linear
Weights:
 [[ 0.1  0.3  0.2]
 [ 0.4  0.2 -0.7]
 [ 0.1 -0.8  0.5]]


In [11]:
fit(the_model, parser)

Start Training for MLP
Epoch 1 completed
Loss: 0.665
Training Accuracy: 100.0%


In [12]:
the_model.summary()

Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: linear
Weights:
 [[ 0.22  0.36  0.11]
 [ 0.64  0.3  -0.89]
 [ 0.28 -0.7   0.37]]


## TestCase for mlp

In [13]:
parser = BackPropParser("../test_case/B/mlp.json")
the_model = parser.build_model()
the_model.summary()




Summary for Model: the_model
Layer: hidden1 | Type: hidden | Output shape: 2 | Activation function: linear
Weights:
 [[ 0.1  0.2]
 [-0.3  0.5]
 [ 0.4  0.5]]
_____________________________________
Layer: output1 | Type: output | Output shape: 2 | Activation function: relu
Weights:
 [[ 0.2  0.1]
 [ 0.4 -0.5]
 [ 0.7  0.8]]


In [14]:
fit(the_model, parser)

Start Training for MLP
Epoch 1 completed
Loss: 0.676952
Training Accuracy: 100.0%


In [15]:
the_model.summary()

Summary for Model: the_model
Layer: hidden1 | Type: hidden | Output shape: 2 | Activation function: linear
Weights:
 [[ 0.08592   0.32276 ]
 [-0.33872   0.46172 ]
 [ 0.449984  0.440072]]
_____________________________________
Layer: output1 | Type: output | Output shape: 2 | Activation function: relu
Weights:
 [[ 0.2748    0.188   ]
 [ 0.435904 -0.53168 ]
 [ 0.68504   0.7824  ]]


## TestCase for relu_b

In [16]:
parser = BackPropParser("../test_case/B/relu_b.json")
the_model = parser.build_model()
the_model.summary()




Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: relu
Weights:
 [[-0.2  0.2  1. ]
 [ 0.3  0.5  0.5]
 [-0.5 -1.   0.5]]


In [17]:
fit(the_model, parser)

Start Training for MLP
Epoch 1 completed
Loss: 2.7935499999999998
Training Accuracy: 0.0%


In [18]:
the_model.summary()

Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: relu
Weights:
 [[-0.211   0.105   0.885 ]
 [ 0.3033  0.5285  0.3005]
 [-0.489  -0.905   0.291 ]]


## TestCase for sigmoid

In [19]:
parser = BackPropParser("../test_case/B/sigmoid.json")
the_model = parser.build_model()
the_model.summary()




Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 2 | Activation function: sigmoid
Weights:
 [[0.3 0.1]
 [0.2 0.6]
 [0.8 0.3]]


In [20]:
fit(the_model, parser)

Start Training for MLP
Epoch 1 completed
Loss: 0.4728101406019331
Training Accuracy: 100.0%
Epoch 2 completed
Loss: 0.47078073489758887
Training Accuracy: 100.0%
Epoch 3 completed
Loss: 0.46876757811986325
Training Accuracy: 100.0%
Epoch 4 completed
Loss: 0.4667706588834645
Training Accuracy: 100.0%
Epoch 5 completed
Loss: 0.4647899555600068
Training Accuracy: 100.0%
Epoch 6 completed
Loss: 0.4628254366344452
Training Accuracy: 100.0%
Epoch 7 completed
Loss: 0.46087706106867526
Training Accuracy: 100.0%
Epoch 8 completed
Loss: 0.45894477867098016
Training Accuracy: 100.0%
Epoch 9 completed
Loss: 0.4570285304700267
Training Accuracy: 100.0%
Epoch 10 completed
Loss: 0.4551282490921642
Training Accuracy: 100.0%


In [21]:
the_model.summary()

Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 2 | Activation function: sigmoid
Weights:
 [[0.23291176 0.06015346]
 [0.12884088 0.64849474]
 [0.837615   0.23158199]]


## TestCase for softmax_two_layer

In [22]:
parser = BackPropParser("../test_case/B/softmax_two_layer.json")

In [23]:
the_model = parser.build_model()

In [24]:
the_model.summary()

Summary for Model: the_model
Layer: hidden1 | Type: hidden | Output shape: 4 | Activation function: relu
Weights:
 [[ 0.1 -0.1  0.1 -0.1]
 [-0.1  0.1 -0.1  0.1]
 [ 0.1  0.1 -0.1 -0.1]]
_____________________________________
Layer: output1 | Type: output | Output shape: 2 | Activation function: softmax
Weights:
 [[ 0.12 -0.1 ]
 [-0.12  0.1 ]
 [ 0.12 -0.1 ]
 [-0.12  0.1 ]
 [ 0.02  0.  ]]


In [25]:
fit(the_model, parser)

Start Training for MLP
Epoch 1 completed
Loss: 0.7441914873791614
Training Accuracy: 62.5%
Epoch 2 completed
Loss: 0.719297568780222
Training Accuracy: 75.0%
Epoch 3 completed
Loss: 0.712065197860922
Training Accuracy: 75.0%
Epoch 4 completed
Loss: 0.7046647860005425
Training Accuracy: 75.0%
Epoch 5 completed
Loss: 0.6952825455473035
Training Accuracy: 62.5%
Epoch 6 completed
Loss: 0.6869383012660022
Training Accuracy: 62.5%
Epoch 7 completed
Loss: 0.6694747046307074
Training Accuracy: 75.0%
Epoch 8 completed
Loss: 0.6453807082887808
Training Accuracy: 75.0%
Epoch 9 completed
Loss: 0.6199787183393141
Training Accuracy: 75.0%
Epoch 10 completed
Loss: 0.5678508847947743
Training Accuracy: 100.0%
Epoch 11 completed
Loss: 0.5193498293586598
Training Accuracy: 87.5%
Epoch 12 completed
Loss: 0.4698520610627104
Training Accuracy: 100.0%
Epoch 13 completed
Loss: 0.41842674180042283
Training Accuracy: 100.0%
Epoch 14 completed
Loss: 0.35501399877193796
Training Accuracy: 100.0%
Epoch 15 complet

In [26]:
the_model.summary()

Summary for Model: the_model
Layer: hidden1 | Type: hidden | Output shape: 4 | Activation function: relu
Weights:
 [[-0.28730211 -0.28822282 -0.70597451  0.42094471]
 [-0.5790794  -1.1836444  -1.34287961  0.69575311]
 [-0.41434377  1.51314676 -0.97649086 -1.3043465 ]]
_____________________________________
Layer: output1 | Type: output | Output shape: 2 | Activation function: softmax
Weights:
 [[-1.72078607  1.74078607]
 [-0.50352956  0.48352956]
 [ 1.25764816 -1.23764816]
 [-1.16998784  1.14998784]
 [ 1.0907634  -1.0707634 ]]


## TestCase for softmax

In [27]:
parser = BackPropParser("../test_case/B/softmax.json")
the_model = parser.build_model()
the_model.summary()




Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: softmax
Weights:
 [[ 0.1  0.9 -0.1]
 [-0.2  0.8  0.2]
 [ 0.3 -0.7  0.3]
 [ 0.4  0.6 -0.4]
 [ 0.5  0.5  0.5]
 [-0.6  0.4  0.6]
 [-0.7 -0.3  0.7]
 [ 0.8  0.2 -0.8]
 [ 0.9 -0.1  0. ]]


In [28]:
fit(the_model, parser)

Start Training for MLP
Epoch 1 completed
Loss: 2.7316518208880467
Training Accuracy: 0.0%
Epoch 2 completed
Loss: 2.3896045613471406
Training Accuracy: 0.0%
Epoch 3 completed
Loss: 2.0990617798758477
Training Accuracy: 66.66666666666666%
Epoch 4 completed
Loss: 1.85060398040073
Training Accuracy: 66.66666666666666%
Epoch 5 completed
Loss: 1.633210744618274
Training Accuracy: 66.66666666666666%
Epoch 6 completed
Loss: 1.4386893459158283
Training Accuracy: 66.66666666666666%
Epoch 7 completed
Loss: 1.262109742703961
Training Accuracy: 66.66666666666666%
Epoch 8 completed
Loss: 1.1009651865542056
Training Accuracy: 66.66666666666666%
Epoch 9 completed
Loss: 0.9543661075958426
Training Accuracy: 66.66666666666666%
Epoch 10 completed
Loss: 0.822408775339098
Training Accuracy: 66.66666666666666%


In [29]:
the_model.summary()

Summary for Model: the_model
Layer: output1 | Type: output | Output shape: 3 | Activation function: softmax
Weights:
 [[ 0.12674605  0.9149538  -0.14169985]
 [-0.33551647  0.67700488  0.45851159]
 [ 0.48314436 -0.85241216  0.2692678 ]
 [ 0.3400255   0.57237542 -0.31240092]
 [ 0.31397716  0.46349737  0.72252547]
 [-0.69652442  0.4789189   0.61760552]
 [-0.50884515 -0.36354141  0.57238656]
 [ 0.41891295  0.26354517 -0.48245812]
 [ 0.90374164 -0.01759501 -0.08614663]]


# Test for Iris Data

In [30]:
#perform preprocessing
processor = PreProcessing()
processor.readCSV("../test_case/testcase_dataset/iris.csv")
df = processor.data_frame

In [31]:
#change the species to one hot encoding, example: [0,0,1] 
Y = np.array(pd.get_dummies(df['Species']))
#change from boolean to int
Y = Y.astype(np.float64)

X = np.array(df.drop(columns=['Id','Species']))

In [32]:
#acak data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.05, random_state=42)

In [33]:
the_model= Model("Iris", ANN(X_train.shape[1], Y_train.shape[1], 0.1, 100))
# CREATE MLP
# HIDDEN LAYER 1 : INPUT = 4, OUTPUT = 15
# HIDDEN LAYER 2 : INPUT = 15, OUTPUT = 10
# OUTPUT LAYER : INPUT = 10, OUTPUT = 3
shape1 = (X_train.shape[1]+1, 15)
W1 = the_model.init_weight(shape1)
shape2 = (16,10)
W2 = the_model.init_weight(shape2)
shape3 = (11, 3)
W3 = the_model.init_weight(shape3)

(5, 15)
(16, 10)
(11, 3)


In [34]:
the_model.add(HiddenLayer("Hidden_1",X_train.shape[1], 15, W1, "relu"))
the_model.add(HiddenLayer("Hidden_2",15, 10, W2, "relu"))
the_model.add(OutputLayer("Output",10, 3, W3, "softmax", Y_train))

In [35]:
the_model.fit(X_train, Y_train,1000,0.0001,5)

Start Training for MLP
Epoch 1 completed
Loss: 12.23451023543902
Training Accuracy: 33.098591549295776%
Epoch 2 completed
Loss: 6.167759876720408
Training Accuracy: 54.22535211267606%
Epoch 3 completed
Loss: 2.6089123774022926
Training Accuracy: 72.53521126760563%
Epoch 4 completed
Loss: 1.7405426158655677
Training Accuracy: 80.98591549295774%
Epoch 5 completed
Loss: 1.161525134181492
Training Accuracy: 85.91549295774648%
Epoch 6 completed
Loss: 0.7952887747564948
Training Accuracy: 85.91549295774648%
Epoch 7 completed
Loss: 1.1472840071201058
Training Accuracy: 86.61971830985915%
Epoch 8 completed
Loss: 1.174182027098641
Training Accuracy: 86.61971830985915%
Epoch 9 completed
Loss: 1.1400922971757121
Training Accuracy: 88.02816901408451%
Epoch 10 completed
Loss: 1.1086597415405437
Training Accuracy: 90.14084507042254%
Epoch 11 completed
Loss: 1.116817437129201
Training Accuracy: 90.14084507042254%
Epoch 12 completed
Loss: 1.0450550670789551
Training Accuracy: 88.02816901408451%
Epoch 

Training Accuracy: 91.54929577464789%
Epoch 30 completed
Loss: 0.415781780277842
Training Accuracy: 91.54929577464789%
Epoch 31 completed
Loss: 0.3399180373221586
Training Accuracy: 91.54929577464789%
Epoch 32 completed
Loss: 0.3278708971833305
Training Accuracy: 90.84507042253522%
Epoch 33 completed
Loss: 0.30960536593982335
Training Accuracy: 90.84507042253522%
Epoch 34 completed
Loss: 0.28746243891502193
Training Accuracy: 90.84507042253522%
Epoch 35 completed
Loss: 0.2677051040577156
Training Accuracy: 90.84507042253522%
Epoch 36 completed
Loss: 0.2574416395323887
Training Accuracy: 90.84507042253522%
Epoch 37 completed
Loss: 0.249956388536479
Training Accuracy: 90.84507042253522%
Epoch 38 completed
Loss: 0.24376249424300134
Training Accuracy: 91.54929577464789%
Epoch 39 completed
Loss: 0.23824712192657246
Training Accuracy: 91.54929577464789%
Epoch 40 completed
Loss: 0.2330331514765485
Training Accuracy: 91.54929577464789%
Epoch 41 completed
Loss: 0.22797401227566108
Training Accu

In [36]:
the_model.save("../saved_model/mlp_iris.pkl")

In [37]:
the_model.predict(X_train, Y_train)

Validation Accuracy: 98.59154929577466%


array([1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2], dtype=int64)

In [38]:
loaded_model = Model.load("../saved_model/mlp_iris.pkl")

In [39]:
loaded_model.summary()

Summary for Model: Iris
Layer: Hidden_1 | Type: hidden | Output shape: 15 | Activation function: relu
Weights:
 [[ 0.52916056 -0.49410155 -3.87197255  2.6694247  -1.22695696 -1.094878
   2.26731014 -0.11671489  1.91495397 -1.55933535  0.59938933 -0.48872727
  -1.99628218  1.56285371  0.26405149]
 [-2.19483376 -0.48142561  3.79476582  5.34589027 -1.15247822  2.04525587
  -2.79859447 -0.86129867  5.46207557 -1.79715705 -1.25331668 -1.85854352
   2.26596375  0.58701111 -2.13234236]
 [ 1.5735786  -0.50274702  1.88600071  0.95052413 -0.88815987  2.7754711
   0.56548065  0.13044199 -1.13741482  0.99392337  0.8145867   0.12800218
   1.14007785  0.43147554  3.25312166]
 [-1.30864072  2.56336698  1.58223153 -0.02310669 -2.12131381 -0.29267478
  -2.83837152  1.83649288 -1.15611182 -1.78312421  1.22602205  0.87844598
  -0.97156984 -0.75958616  2.72146602]
 [-1.82601082  1.20793822  0.22054495 -0.85881268  0.28654739  1.04715228
   1.8942951  -0.08187452  0.58512436  0.69549745 -1.19900248 -0.6838

In [40]:
result = loaded_model.predict(X_test,Y_test)
print("predicted class result : ", result)

Validation Accuracy: 100.0%
predicted class result :  [1 0 2 1 1 0 1 2]
