In [33]:
from lib import *

TypeError: 'module' object is not callable

In [22]:
import numpy as np
import pandas as pd

In [29]:
data = PreProcessing("../testcase_dataset/iris.csv")

TypeError: 'module' object is not callable

In [ ]:
W1 = np.array(
    [[0.35, 0.35]
     ,[0.15, 0.25]
    ,[0.20, 0.30]]
    )

In [ ]:
W2 = np.array(
    [[0.60, 0.60, 0.5]
    ,[0.40, 0.50, 0.4],
    [0.45, 0.55, 0.2]]
    )

In [ ]:
X = np.array([[0.05, 0.10],[0.2,0.3]])
Y = np.array([[0, 1, 0],[0, 0, 1]])

In [ ]:
model = Model("ajg",ANN(2,3))

In [ ]:
layer1 = HiddenLayer("hidden1",2,2,W1,"sigmoid")
layer2 = OutputLayer("hidden2",2,3,W2,"softmax",Y)
model.add(layer1)
model.add(layer2)

In [ ]:
model.summary()

In [ ]:
model.predict(X)

In [ ]:
model.test_backward()

In [ ]:
"""
coba testcase dari asisten buat sigmoid
{
    "case": {
        "model": {
            "input_size": 2,
            "layers": [
                {
                    "number_of_neurons": 2,
                    "activation_function": "sigmoid"
                }
            ]
        },
        "input": [
            [0.5, 0.0],
            [0.0, 0.5]
        ],
        "initial_weights": [
            [
              [0.3, 0.1], 
		  [0.2, 0.6],
		  [0.8, 0.3]
            ]
        ],
        "target": [
            [0.0, 1.0],
            [1.0, 0.0]
        ],
        "learning_parameters": {
            "learning_rate": 0.1,
            "batch_size": 2,
            "max_iteration": 10,
            "error_threshold": 0.01
        }
    },
    "expect": {
        "stopped_by": "max_iteration",
	  "final_weights":[
		 [
			[0.2329, 0.0601],
			[0.1288, 0.6484],
			[0.8376, 0.2315]
		 ]
	  ]
    }
}
"""

In [ ]:
W = np.array([
              [0.3, 0.1], 
		    [0.2, 0.6],
		    [0.8, 0.3]
            ])

In [ ]:
X = np.array([
            [0.5, 0.0],
            [0.0, 0.5]
            ])
Y = np.array([
            [0.0, 1.0],
            [1.0, 0.0]
            ])


In [20]:
model2 = Model("ajg",ANN(2,2,learning_rate=0.1))
model2.add(OutputLayer("output1",2,2,W,"sigmoid",Y))
model2.summary()

NameError: name 'W' is not defined

In [19]:
model2.fit(X,Y,10,0.1,batch_size=2,error_threshold=0.01)

NameError: name 'model2' is not defined

In [ ]:
model2.summary()

# Hasilnya sama gan

In [ ]:
"""
Coba Softmax
{
    "case": {
        "model": {
            "input_size": 8,
            "layers": [
                {
                    "number_of_neurons": 3,
                    "activation_function": "softmax"
                }
            ]
        },
        "input": [
            [-2.4, -2.78, -0.6, 0.37, 2.46, -0.92, 2.76, 2.62],
            [-1.79, 1.65, -0.77, -1.03, 0.1, 2.12, -2.36, 1.25],
            [1.65, 2.34, 0.27, 2.34, 0.52, 1.37, 1.77, 0.62]
        ],
        "initial_weights": [
            [
                [0.1, 0.9, -0.1],
                [-0.2, 0.8, 0.2],
                [0.3, -0.7, 0.3],
                [0.4, 0.6, -0.4],
                [0.5, 0.5, 0.5],
                [-0.6, 0.4, 0.6],
                [-0.7, -0.3, 0.7],
                [0.8, 0.2, -0.8],
                [0.9, -0.1, 0.0]
            ]
        ],
        "target": [
            [0, 1, 0],
            [1, 0, 0],
            [0, 0, 1]
        ],
        "learning_parameters": {
            "learning_rate": 0.01,
            "batch_size": 1,
            "max_iteration": 10,
            "error_threshold": 0.05
        }
    },
    "expect": {
        "stopped_by": "max_iteration",
        "final_weights": [
            [
                [ 0.12674605,  0.9149538,  -0.14169985],
                [-0.33551647,  0.67700488,  0.45851159],
                [ 0.48314436, -0.85241216,  0.2692678 ],
                [ 0.3400255,   0.57237542, -0.31240092],
                [ 0.31397716,  0.46349737,  0.72252547],
                [-0.69652442,  0.4789189,   0.61760552],
                [-0.50884515, -0.36354141,  0.57238656],
                [ 0.41891295,  0.26354517, -0.48245812],
                [ 0.90374164, -0.01759501, -0.08614663]
            ]
        ]
    }
}
"""

In [ ]:
X = np.array([
            [-2.4, -2.78, -0.6, 0.37, 2.46, -0.92, 2.76, 2.62],
            [-1.79, 1.65, -0.77, -1.03, 0.1, 2.12, -2.36, 1.25],
            [1.65, 2.34, 0.27, 2.34, 0.52, 1.37, 1.77, 0.62]
        ])
Y = np.array([
            [0, 1, 0],
            [1, 0, 0],
            [0, 0, 1]
        ])

In [ ]:
model3 = Model("ajg",ANN(8,3,learning_rate=0.01))
W = np.array([
                [0.1, 0.9, -0.1],
                [-0.2, 0.8, 0.2],
                [0.3, -0.7, 0.3],
                [0.4, 0.6, -0.4],
                [0.5, 0.5, 0.5],
                [-0.6, 0.4, 0.6],
                [-0.7, -0.3, 0.7],
                [0.8, 0.2, -0.8],
                [0.9, -0.1, 0.0]
            ])
model3.add(OutputLayer("output1",8,3,W,"softmax",Y))

In [ ]:
model3.fit(X,Y,10,0.01,batch_size=1,error_threshold=0.05)

In [ ]:
model3.summary()

In [ ]:
"""
{
    "case": {
        "model": {
            "input_size": 2,
            "layers": [
                {
                    "number_of_neurons": 3,
                    "activation_function": "linear"
                }
            ]
        },
        "input": [
            [3.0, 1.0],
            [1.0, 2.0]
        ],
        "initial_weights": [
            [
              [0.1, 0.3, 0.2],
              [0.4, 0.2, -0.7],
              [0.1, -0.8, 0.5]
            ]
        ],
        "target": [
            [ 2.0,  0.3, -1.9],
            [ 1.3, -0.7,  0.1]
        ],
        "learning_parameters": {
            "learning_rate": 0.1,
            "batch_size": 2,
            "max_iteration": 2,
            "error_threshold": 0.0
        }
    },
    "expect": {
        "stopped_by": "max_iteration",
        "final_weights": [
            [
              [ 0.166,  0.338, 0.153],
              [ 0.502,  0.226, -0.789],
              [ 0.214, -0.718,  0.427]
            ]
        ]
    }
}
"""

In [ ]:
model4 = Model("ajg",ANN(2,3,learning_rate=0.1))
W = np.array([
              [0.1, 0.3, 0.2],
              [0.4, 0.2, -0.7],
              [0.1, -0.8, 0.5]
            ])
X = np.array([
            [3.0, 1.0],
            [1.0, 2.0]
            ])
Y = np.array([
            [ 2.0,  0.3, -1.9],
            [ 1.3, -0.7,  0.1]
            ])

model4.add(OutputLayer("output1",2,3,W,"linear",Y))

In [ ]:
model4.fit(X,Y,2,0.1,batch_size=2,error_threshold=0.0)

In [ ]:
model4.summary()

In [ ]:
x = np.array([1,2,2,1,3])
#sort descending
x.sort()

In [ ]:
print(x)

In [32]:
parser = BackPropParser("../test_case/B/softmax_two_layer.json")

In [33]:
the_model = parser.build_model()

In [34]:
the_model.summary()

Summary for Model: the_model
Layer: hidden1 | Type: hidden | Output shape: 4
Weights:
 [[ 0.1 -0.1  0.1 -0.1]
 [-0.1  0.1 -0.1  0.1]
 [ 0.1  0.1 -0.1 -0.1]]
_____________________________________
Layer: output1 | Type: output | Output shape: 2
Weights:
 [[ 0.12 -0.1 ]
 [-0.12  0.1 ]
 [ 0.12 -0.1 ]
 [-0.12  0.1 ]
 [ 0.02  0.  ]]
