In [1]:
from lib import *

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
data = PreProcessing()

In [4]:
parser = BackPropParser("../test_case/B/softmax_two_layer.json")

In [5]:
the_model = parser.build_model()

In [6]:
the_model.summary()

Summary for Model: the_model
Layer: hidden1 | Type: hidden | Output shape: 4 | Activation function: relu
Weights:
 [[ 0.1 -0.1  0.1 -0.1]
 [-0.1  0.1 -0.1  0.1]
 [ 0.1  0.1 -0.1 -0.1]]
_____________________________________
Layer: output1 | Type: output | Output shape: 2 | Activation function: softmax
Weights:
 [[ 0.12 -0.1 ]
 [-0.12  0.1 ]
 [ 0.12 -0.1 ]
 [-0.12  0.1 ]
 [ 0.02  0.  ]]


In [7]:
the_model.fit(parser.input, parser.target, parser.max_iteration, parser.learning_rate, parser.batch_size, error_threshold=parser.error_threshold)

Epoch 1 completed
Loss: 0.7441914873791614
[[0.         0.06344318 0.         0.        ]
 [0.23426368 0.10094113 0.         0.        ]
 [0.31794286 0.         0.42884574 0.        ]
 [0.34519884 0.10045383 0.00253638 0.        ]
 [0.37817068 0.0223826  0.24202685 0.        ]
 [0.41399909 0.         0.56576626 0.        ]
 [0.         0.         0.22726051 0.25352761]
 [0.         0.09548602 0.         0.        ]]
[[0.5428003  0.4571997 ]
 [0.53480228 0.46519772]
 [0.50282145 0.49717855]
 [0.53034935 0.46965065]
 [0.5124228  0.4875772 ]
 [0.49080017 0.50919983]
 [0.53006258 0.46993742]
 [0.54368548 0.45631452]]
Accuracy: 62.5%
Epoch 2 completed
Loss: 0.719297568780222
[[0.         0.         0.         0.        ]
 [0.11290476 0.12984721 0.         0.        ]
 [0.32240082 0.04536277 0.49659304 0.        ]
 [0.23743932 0.20066235 0.         0.        ]
 [0.32030591 0.16699192 0.26961637 0.        ]
 [0.42596156 0.11177661 0.66742201 0.        ]
 [0.         0.         0.23658427 0.26

In [8]:
the_model.summary()

Summary for Model: the_model
Layer: hidden1 | Type: hidden | Output shape: 4 | Activation function: relu
Weights:
 [[-0.28730211 -0.28822282 -0.70597451  0.42094471]
 [-0.5790794  -1.1836444  -1.34287961  0.69575311]
 [-0.41434377  1.51314676 -0.97649086 -1.3043465 ]]
_____________________________________
Layer: output1 | Type: output | Output shape: 2 | Activation function: softmax
Weights:
 [[-1.72078607  1.74078607]
 [-0.50352956  0.48352956]
 [ 1.25764816 -1.23764816]
 [-1.16998784  1.14998784]
 [ 1.0907634  -1.0707634 ]]


In [9]:
processor = PreProcessing()
processor.readCSV("../test_case/testcase_dataset/iris.csv")

In [10]:
df = processor.data_frame

In [11]:
#change the species to one hot encoding, example: [0,0,1] 
Y = pd.get_dummies(df['Species'])
#change from boolean to int
Y = Y.astype(np.float64)

X = df.drop(columns=['Id','Species'])

#preprocess Y 


In [12]:
Y

Iris-setosa  Iris-versicolor  Iris-virginica
0            1.0              0.0             0.0
1            1.0              0.0             0.0
2            1.0              0.0             0.0
3            1.0              0.0             0.0
4            1.0              0.0             0.0
..           ...              ...             ...
145          0.0              0.0             1.0
146          0.0              0.0             1.0
147          0.0              0.0             1.0
148          0.0              0.0             1.0
149          0.0              0.0             1.0

[150 rows x 3 columns]

In [13]:

#acak data
X_train, X_test, Y_train, Y_test = train_test_split(X.to_numpy(), Y.to_numpy(), test_size=0.2, random_state=42)

In [14]:
print(X_train.shape)

(120, 4)


In [15]:
#predict
the_model = Model("Iris", ANN(X_train.shape[1], Y_train.shape[1], 0.1, 100))

In [17]:
the_model.add(HiddenLayer("Hidden_1",X_train.shape[1], 100, np.ones((X_train.shape[1]+1, 100)), "sigmoid"))
the_model.add(HiddenLayer("Hidden_2",100, 50, np.ones((101, 50)), "sigmoid"))
the_model.add(OutputLayer("Output",50, 3, np.ones((51, 3)), "softmax", None))

In [20]:
# perform minmax scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
the_model.predict(np.array([[1,23,3,4],
                           [-100000,5,3,7]]))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]
[[1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.  

d:\programming\python\tubes_ML\src\lib\ActivationFunction.py:11: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-Z))


array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])